[namenode]

host = 'localhost'
publicPort = 7070
privatePort = 7071

treeUpdatePeriod = 10
treeLogName = 'tree.log'
treeGobName = 'tree.gob'
chunkTableGobName = 'chunks.gob'
softDeathTime = 5#21
hardDeathTime = 10#180

chunkSize = 2 # mb
#heartBeatPort = 7001
replicas = 4
storagePrivatePort = 7001

#[[storage]]
#host = 'localhost'
#port = 7777

#[[storage]]
#host = '127.0.0.1'
#port = 7001
[[storage]]
host = '10.0.0.1'
[[storage]]
host = '10.0.0.2'
[[storage]]
host = '10.0.0.3'
[[storage]]
host = '10.0.0.4'
[[storage]]
host = '10.0.0.5'
[[storage]]
host = '10.0.0.6'
