[namenode]

host = '10.91.90.77'
publicPort = 7070
privatePort = 7071

treeUpdatePeriod = 10
treeLogName = 'tree.log'
treeGobName = 'tree.gob'
chunkTableGobName = 'chunks.gob'
softDeathTime = 5#21
hardDeathTime = 10#180

chunkSize = 2 # mb
#heartBeatPort = 7001
replicas = 2
fsPublicPort = 7000
fsPrivatePort = 7001


[[storage]]
host = '10.91.84.229'
publicHost = '10.91.84.229'
[[storage]]
host = '10.91.81.59'
publicHOst = '10.91.81.59'
#[[storage]]
#host = '10.0.0.3'
#publicHost = 'localhost3'
#[[storage]]
#host = '10.0.0.4'
#[[storage]]
#host = '10.0.0.5'
#[[storage]]
#host = '10.0.0.6'
